/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IRollupVerifier, IRollupVerifierInterface } from "../IRollupVerifier.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "proof",
        "type": "bytes"
      },
      {
        "internalType": "uint256[]",
        "name": "publicSignals",
        "type": "uint256[]"
      }
    ],
    "name": "verifyProof",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IRollupVerifier__factory {
    static readonly abi = _abi;
    static createInterface(): IRollupVerifierInterface {
      return new Interface(_abi) as IRollupVerifierInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IRollupVerifier {
      return new Contract(address, _abi, runner) as unknown as IRollupVerifier;
    }
  }
  