/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../common.js"
  import type { MockVerifier, MockVerifierInterface } from "../MockVerifier.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "proof",
        "type": "bytes"
      },
      {
        "internalType": "uint256[]",
        "name": "publicSignals",
        "type": "uint256[]"
      }
    ],
    "name": "setExpected",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "validProofHash",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "validPublicSignalsHash",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "proof",
        "type": "bytes"
      },
      {
        "internalType": "uint256[]",
        "name": "publicSignals",
        "type": "uint256[]"
      }
    ],
    "name": "verifyProof",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080604052348015600e575f5ffd5b506102948061001c5f395ff3fe608060405234801561000f575f5ffd5b506004361061004a575f3560e01c80631e8e1e131461004e578063597b689214610076578063aeee52741461008b578063e7eec10b146100a2575b5f5ffd5b61006161005c366004610150565b6100aa565b60405190151581526020015b60405180910390f35b610089610084366004610150565b610104565b005b61009460015481565b60405190815260200161006d565b6100945f5481565b5f5f5485856040516100bd929190610218565b60405180910390201480156100fb575060015483836040516020016100e3929190610227565b60405160208183030381529060405280519060200120145b95945050505050565b8383604051610114929190610218565b6040519081900381205f5561012f9083908390602001610227565b60408051601f19818403018152919052805160209091012060015550505050565b5f5f5f5f60408587031215610163575f5ffd5b843567ffffffffffffffff811115610179575f5ffd5b8501601f81018713610189575f5ffd5b803567ffffffffffffffff81111561019f575f5ffd5b8760208284010111156101b0575f5ffd5b60209182019550935085013567ffffffffffffffff8111156101d0575f5ffd5b8501601f810187136101e0575f5ffd5b803567ffffffffffffffff8111156101f6575f5ffd5b8760208260051b840101111561020a575f5ffd5b949793965060200194505050565b818382375f9101908152919050565b602080825281018290525f6001600160fb1b03831115610245575f5ffd5b8260051b8085604085013791909101604001939250505056fea26469706673582212206860268880f051012f81951f04801a9f8a9813015c323faa014c1ea4cef2da9564736f6c634300081c0033";

  
      type MockVerifierConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MockVerifierConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MockVerifier__factory extends ContractFactory {
    
      constructor(...args: MockVerifierConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<MockVerifier & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MockVerifier__factory {
      return super.connect(runner) as MockVerifier__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MockVerifierInterface {
      return new Interface(_abi) as MockVerifierInterface;
    }
    
    override attach(address: string | Addressable): MockVerifier {
      return super.attach(address) as MockVerifier;
    }
  static connect(address: string, runner?: ContractRunner | null): MockVerifier {
      return new Contract(address, _abi, runner) as unknown as MockVerifier;
    }
  }

  
  