/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IRollupGroth16Verifier, IRollupGroth16VerifierInterface } from "../../RollupVerifierAdapter.sol/IRollupGroth16Verifier.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256[2]",
        "name": "pA",
        "type": "uint256[2]"
      },
      {
        "internalType": "uint256[2][2]",
        "name": "pB",
        "type": "uint256[2][2]"
      },
      {
        "internalType": "uint256[2]",
        "name": "pC",
        "type": "uint256[2]"
      },
      {
        "internalType": "uint256[3]",
        "name": "pubSignals",
        "type": "uint256[3]"
      }
    ],
    "name": "verifyProof",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IRollupGroth16Verifier__factory {
    static readonly abi = _abi;
    static createInterface(): IRollupGroth16VerifierInterface {
      return new Interface(_abi) as IRollupGroth16VerifierInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IRollupGroth16Verifier {
      return new Contract(address, _abi, runner) as unknown as IRollupGroth16Verifier;
    }
  }
  