/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IRollupGroth16Verifier } from './IRollupGroth16Verifier.js';
export type { RollupVerifierAdapter } from './RollupVerifierAdapter.js';