/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface MiniRollupInterface extends Interface {
    getFunction(nameOrSignature: "stateRoot" | "submitBatch" | "verifier"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "BatchSubmitted"): EventFragment;

    encodeFunctionData(functionFragment: 'stateRoot', values?: undefined): string;
encodeFunctionData(functionFragment: 'submitBatch', values: [BytesLike, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'verifier', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'stateRoot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitBatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifier', data: BytesLike): Result;
  }

  
    export namespace BatchSubmittedEvent {
      export type InputTuple = [oldRoot: BigNumberish, newRoot: BigNumberish, batchHash: BigNumberish];
      export type OutputTuple = [oldRoot: bigint, newRoot: bigint, batchHash: bigint];
      export interface OutputObject {oldRoot: bigint, newRoot: bigint, batchHash: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MiniRollup extends BaseContract {
    
    connect(runner?: ContractRunner | null): MiniRollup;
    waitForDeployment(): Promise<this>;

    interface: MiniRollupInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    stateRoot: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    submitBatch: TypedContractMethod<
      [proof: BytesLike, oldRoot: BigNumberish, newRoot: BigNumberish, batchHash: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    verifier: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'stateRoot'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'submitBatch'): TypedContractMethod<
      [proof: BytesLike, oldRoot: BigNumberish, newRoot: BigNumberish, batchHash: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'verifier'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'BatchSubmitted'): TypedContractEvent<BatchSubmittedEvent.InputTuple, BatchSubmittedEvent.OutputTuple, BatchSubmittedEvent.OutputObject>;

    filters: {
      
      'BatchSubmitted(uint256,uint256,uint256)': TypedContractEvent<BatchSubmittedEvent.InputTuple, BatchSubmittedEvent.OutputTuple, BatchSubmittedEvent.OutputObject>;
      BatchSubmitted: TypedContractEvent<BatchSubmittedEvent.InputTuple, BatchSubmittedEvent.OutputTuple, BatchSubmittedEvent.OutputObject>;
    
    };
  }